version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - default
      - main_web_server
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    expose:
      - "80"
      - "443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - default
      - main_web_server
  db:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: zibayi
      MYSQL_ROOT_PASSWORD: zibayi
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
    volumes:
      - ./mysql:/var/lib/mysql/

#Docker Networks
networks:
  main_web_server:
    external:
      name: main_web_server
